import test_data

test_data.run_data("results.pkl", "elo.pkl", 0)
test_data.reset("elo.pkl")
test_data.run_data("results.pkl", "elo.pkl", 5)
test_data.reset("elo.pkl")
test_data.run_data("results.pkl", "elo.pkl", 10)
test_data.reset("elo.pkl")
test_data.run_data("results.pkl", "elo.pkl", 15)
test_data.reset("elo.pkl")
test_data.run_data("results.pkl", "elo.pkl", 20)
test_data.reset("elo.pkl")
test_data.run_data("results.pkl", "elo.pkl", 25)
test_data.reset("elo.pkl")
test_data.run_data("results.pkl", "elo.pkl", 30)
test_data.reset("elo.pkl")
test_data.run_data("results.pkl", "elo.pkl", 35)
test_data.reset("elo.pkl")
test_data.run_data("results.pkl", "elo.pkl", 40)
test_data.reset("elo.pkl")
